"""initial schema

Revision ID: d4042351afdb
Revises:
Created: 2026-09-25 16:08:53.719834
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d4042351afdb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_tier", sa.String(length=32), nullable=True),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("completed_items", sa.Integer(), nullable=False),
        sa.Column("failed_items", sa.Integer(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("callback_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_batch_status", "batch_jobs", ["status", "submitted_at"], unique=False)
    op.create_index("ix_batch_user_time", "batch_jobs", ["user_id", "submitted_at"], unique=False)
    op.create_table(
        "inference_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_tier", sa.String(length=32), nullable=True),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("device", sa.String(length=16), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("image_format", sa.String(length=16), nullable=True),
        sa.Column("image_bytes", sa.Integer(), nullable=True),
        sa.Column("top_label", sa.String(length=255), nullable=True),
        sa.Column("top_confidence", sa.Float(), nullable=True),
        sa.Column("num_results", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("preprocess_ms", sa.Float(), nullable=True),
        sa.Column("inference_ms", sa.Float(), nullable=True),
        sa.Column("postprocess_ms", sa.Float(), nullable=True),
        sa.Column("total_ms", sa.Float(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_inference_correlation", "inference_logs", ["correlation_id"], unique=False)
    op.create_index(
        "ix_inference_errors",
        "inference_logs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("success IS false"),
    )
    op.create_index("ix_inference_hash", "inference_logs", ["image_hash"], unique=False)
    op.create_index(
        "ix_inference_model_time",
        "inference_logs",
        ["model_name", "model_version", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inference_user_time", "inference_logs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.Column("artifact_paths", sa.JSON(), nullable=True),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_model_version", "model_versions", ["name", "version"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_version", table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index("ix_inference_user_time", table_name="inference_logs")
    op.drop_index("ix_inference_model_time", table_name="inference_logs")
    op.drop_index("ix_inference_hash", table_name="inference_logs")
    op.drop_index(
        "ix_inference_errors",
        table_name="inference_logs",
        postgresql_where=sa.text("success IS false"),
    )
    op.drop_index("ix_inference_correlation", table_name="inference_logs")
    op.drop_table("inference_logs")
    op.drop_index("ix_batch_user_time", table_name="batch_jobs")
    op.drop_index("ix_batch_status", table_name="batch_jobs")
    op.drop_table("batch_jobs")
    # ### end Alembic commands ###
