"""Package the repository into a zip for upload to a GPU runtime.

The notebook needs the code on the remote machine. This builds a small archive
containing only what a training and export run actually needs.

What is deliberately excluded, and why:

* ``data/`` — 120,000 images, ~500 MB. The notebook re-downloads Tiny-ImageNet
  on the remote machine, where the connection is far faster than uploading it.
* ``models/artifacts/`` — the CPU-exported ONNX files, ~250 MB. The whole point
  of the GPU run is to produce new ones.
* ``.git/``, caches, virtualenvs, logs — noise.

The result is around 300 KB, which uploads in seconds.

Usage::

    python scripts/package_for_colab.py
    # -> ml-engineer-challenge-colab.zip
"""

from __future__ import annotations

import argparse
import fnmatch
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "ml-engineer-challenge-colab.zip"

# Directories skipped wholesale. Matched against any path component.
EXCLUDE_DIRS = {
    ".git",
    ".github",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "htmlcov",
    "node_modules",
    "data",  # re-downloaded remotely; far faster than uploading
    "artifacts",  # regenerated by the GPU run
    ".ipynb_checkpoints",
}

EXCLUDE_GLOBS = [
    "*.pyc",
    "*.pyo",
    "*.onnx",
    "*.engine",
    "*.plan",
    "*.pt",
    "*.pth",
    "*.npz",
    "*.zip",
    # ONNX external-data sidecars. torch's dynamo exporter writes weights to
    # these GUID-named files; they are tens of megabytes of model weights and
    # have no business in a source archive.
    "*.data",
    "coverage.json",
    "coverage.xml",
    "*.log",
    "*.coverage*",
    ".env",  # SECURITY: never ship real secrets to a hosted runtime
    ".DS_Store",
    "Thumbs.db",
]

# Included even though the patterns above would drop them: the registry is
# small, is the contract between training and serving, and the notebook reads
# it. Empty-directory markers keep the expected layout intact.
FORCE_INCLUDE = {
    "models/registry.json",
    "models/artifacts/.gitkeep",
    "data/.gitkeep",
}


def should_skip(rel: Path) -> bool:
    """True if this path is excluded from the archive."""
    if rel.as_posix() in FORCE_INCLUDE:
        return False
    if any(part in EXCLUDE_DIRS for part in rel.parts):
        return True
    return any(fnmatch.fnmatch(rel.name, pattern) for pattern in EXCLUDE_GLOBS)


def build(output: Path = DEFAULT_OUTPUT, root: Path = REPO_ROOT) -> Path:
    """Write the archive and return its path."""
    output = Path(output)
    files: list[Path] = []

    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if should_skip(rel):
            continue
        files.append(rel)

    # ZIP_DEFLATED: the payload is almost entirely source, which compresses
    # to roughly a fifth of its size.
    skipped: list[tuple[str, str]] = []
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for rel in files:
            try:
                zf.write(root / rel, rel.as_posix())
            except (PermissionError, OSError) as exc:
                # A file locked by another program (a spreadsheet open in
                # Excel, an antivirus scan, OneDrive mid-sync) must not abort
                # the whole package. Record it and carry on; the caller checks
                # that nothing *essential* was lost.
                skipped.append((rel.as_posix(), type(exc).__name__))

    if skipped:
        print(f"skipped {len(skipped)} unreadable file(s):")
        for name, reason in skipped[:5]:
            print(f"  - {name} ({reason})")
        if len(skipped) > 5:
            print(f"  ... and {len(skipped) - 5} more")

    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Package the repo for a GPU runtime.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--list", action="store_true", help="List the files included.")
    args = parser.parse_args()

    archive = build(args.output)

    with zipfile.ZipFile(archive) as zf:
        names = zf.namelist()
        raw = sum(info.file_size for info in zf.infolist())

    size_kb = archive.stat().st_size / 1024
    print(f"wrote {archive}")
    print(f"  {len(names)} files | {raw / 1024:.0f} KB raw -> {size_kb:.0f} KB compressed")

    # A sanity check worth having: the notebook is useless without these.
    essential = [
        "models/training/train_classifier.py",
        "models/optimization/export_tensorrt.py",
        "models/validation/validate.py",
        "scripts/download_datasets.py",
        "api/utils/image_processing.py",
        "requirements.txt",
    ]
    missing = [name for name in essential if name not in names]
    if missing:
        print("\nERROR: the archive is missing files the notebook needs:")
        for name in missing:
            print(f"  - {name}")
        return 1

    if args.list:
        print("\ncontents:")
        for name in names:
            print(f"  {name}")

    print("\nAll essential modules present.")
    print("Upload this file when the notebook's setup cell asks for it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
